### ISSUE TITLE
Isolate each submodule

### ISSUE THREAD

**Issue by YonghuiDong** [YonghuiDong/ShinyCardinal#64]
As the shiny app has become quite large,  It will be a lot easier to reuse, maintain, debug and update each submodule if I encapsulate the code into submodules. 

Some times I need to pass module inputs to other modules. It is a bit more complicated and messy if these modules are independent. 

### To-do:
- [x] Add plotMSI submodule
- [x] Add readImzML submodule
- [x] Add preprocessMSI submodule 
> **Note**
> see how I use the `readImzMLServer$msiDataType()` input in `preprocessMSI` submodule

- [x] Add deisotoping submodule
- [x] Add rmBackground submodule
- [x] Add imageAnalysis submodule
- [x] Add PCA submodule
- [x] Add SSC submodule
- [x] Add networkAll submodule
- [x] Add networkSingle submodule
