### ISSUE TITLE
Show ROIs in plot

### ISSUE THREAD

**Issue by YonghuiDong** [YonghuiDong/ShinyCardinal#9]
## Todo

- [x] rewrite selectROI() function

The original `selecrROI` only works in RStudio. It does not support shiny app. 
When multiple runs are included, I need to allow subset runs, otherwise, the selected ROIs will be plotted in different runs.

- [x] Write a makeFactor2() function

I have saved ROIs as a list in the App, unfortunately, `do.call(makeFactor, list)` does not work when for the list of ROIs are selected from different runs. I need to rewrite `makeFactor` function.

- [x] Plot the ROIs.
